# NUMPY Code

In [1]:
# NumPy (Numerical for Python) is the fundamental package for scientific computing with Python. It contains among other things:
#    NumPy is a python library used for working with arrays 
#    a powerful N-dimensional array object
#    sophisticated (broadcasting) functions
#    useful linear algebra, Fourier transform and random number capabilities 
#    Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data
#    Arbitrary data types can be defined. This allows NumPy to seamlessly and speedly integrate with a wide variety of databases
#    Numpy aims to provide an array object that is upto 50X faster than traditional python lists

In [2]:
import pandas as pd
import numpy as np

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.size

3

In [7]:
arr.shape

(3,)

In [8]:
arr.itemsize

4

In [9]:
arr.max()

3

In [10]:
arr.min()

1

In [12]:
# 2D Array
arr2 = np.array([[0,1,2],[3,4,5]])
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
arr2.ndim

2

In [14]:
len(arr2)

2

In [16]:
# ARRAY SLICING

arr3 = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr3[2]

array([35, 40, 45])

In [18]:
arr3[2][2]

45

In [19]:
arr3[1,2]

30

In [25]:
arr3[,1]

SyntaxError: invalid syntax (<ipython-input-25-4c8b23c6db0f>, line 1)

In [26]:
# Arrange- which will return evenly spaced values within a given interval
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
a.size

15

In [31]:
a
a[::-3]

array([14, 11,  8,  5,  2])

In [35]:
# Zeroes and Ones
# Generate arrays of zeroes or ones
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
# RANDOM- numpy also has lots of ways to create random number arrays:
# rand
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1]
np.random.rand(3,2)

array([[0.54034435, 0.24750124],
       [0.94625762, 0.93426578],
       [0.74759252, 0.61582167]])

In [46]:
np.random.rand(2)

array([0.48029692, 0.02762955])

In [47]:
np.random.rand(5,5)

array([[0.71490262, 0.68459805, 0.64778836, 0.487967  , 0.02761623],
       [0.38727758, 0.33032789, 0.9759024 , 0.81010091, 0.79847638],
       [0.78418518, 0.9042014 , 0.27230404, 0.13024587, 0.38522361],
       [0.67543359, 0.64846983, 0.32003753, 0.09162506, 0.3287112 ],
       [0.28936133, 0.49990639, 0.3201119 , 0.34112677, 0.01450544]])

In [50]:
# MAX/MIN/ARGMAX/ARGMIN
# Useful methods for finding max or min values
M1 = np.arange(20)
M1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

M1.max()

In [53]:
M1.max()

19

In [54]:
M1.min()

0

In [56]:
arr.argmax()

2

In [57]:
# ARRAY Operations
arr1 = np.array([[1,2,3],[8,9,10]])
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [58]:
# 1. Adding Arrays
arr1 + arr1

array([[ 2,  4,  6],
       [16, 18, 20]])

In [59]:
# 2. Multiplying arrays
arr1 * arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [60]:
# 3. Subtracting arrays
arr1 - arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [61]:
# 4. Dividing Arrays
arr1/arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [65]:
# Joining two arrays
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [66]:
# Splitting is reverse operation of joining
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [67]:
# If the array has less elements than required, tit will adjust from the end accordingly
arrss = np.array([1,2,3,4,5,6])
newarr = np.array_split(arrss, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [68]:
# Sorting Arrays
arr5 = np.array([3,2,0,1])
print(np.sort(arr5))

[0 1 2 3]


In [78]:
arr6 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr6))

['apple' 'banana' 'cherry']


In [82]:
# NUMPY- Numerical for Python
# It will provide more efficient storage and data operation as size grows
# Numpy's main object is the homogeneous multidimensional array
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
a.ndim

1

In [86]:
a.dtype.name

'int32'

In [87]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
a.itemsize
a.size

15

In [89]:
a[1:3]

array([1, 2])

In [90]:
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [91]:
a[8]

8

In [92]:
a[::-2]

array([14, 12, 10,  8,  6,  4,  2,  0])

In [93]:
x = a.reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
x[2]

array([10, 11, 12, 13, 14])

In [95]:
x[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])